### ISSUE TITLE
SPIKE: Find a way create a 'scrolling through list' style

### ISSUE THREAD

**Issue by Jooones** [SoftwareSandbox/FiAngulartje#29]

**Comment by toonborgers** [comment]
See https://github.com/josex2r/jQuery-SlotMachine for jQuery plugin

**Comment by Jooones** [comment]
See https://github.com/Jooones/FiAngulartje/tree/spikeForSlotmachine and https://github.com/Jooones/FiAngulartje/commit/5d9dbf15dedf1f493a66adc5b9621d2ecfd825db for the spike result
